name = "Zola Docs"
description = "📂 Zola Docs is an easy way to create documentation for your project."
license = "MIT"
homepage = "https://semanticdata.github.io/zola-docs/"
min_version = "0.18.0"
demo = "https://zola-docs.vercel.app/"

[author]
name = "Miguel Pimentel"
homepage = "https://miguelpimentel.do/"

[original]
name = "Roman Soldatenkov"
homepage = "https://codeandmedia.com"
repo = "https://github.com/codeandmedia/zola_easydocs_theme"
